package ai.finalagent.aiclient;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Map;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import ai.finalagent.aiclient.dto.QualityRequest;
import ai.finalagent.aiclient.dto.QualityResult;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

/**
 * The seam between the two languages, read from a payload the Python service produced itself.
 *
 * <p>{@code wire/quality-process.json} is generated by
 * {@code ai-service/tests/test_quality_wire_fixture.py} and that suite fails if the pipeline's output
 * stops matching it, so this test is not checking a hand-written guess about the wire — it is
 * checking Spring's DTOs against the real serializer, in both directions. A field renamed on one
 * side breaks here rather than showing up as a dataset of nulls three steps later.
 */
class QualityWireContractTest {

    private static final ObjectMapper MAPPER = new ObjectMapper();

    private static JsonNode fixture;
    private static QualityResult response;

    @BeforeAll
    static void loadTheCapturedExchange() throws Exception {
        try (InputStream in = QualityWireContractTest.class.getResourceAsStream(
                "/wire/quality-process.json")) {
            assertThat(in).as("run FINALAGENT_UPDATE_QUALITY_FIXTURE=true pytest -q "
                    + "tests/test_quality_wire_fixture.py in ai-service").isNotNull();
            fixture = MAPPER.readTree(new String(in.readAllBytes(), StandardCharsets.UTF_8));
        }
        response = MAPPER.treeToValue(fixture.get("response"), QualityResult.class);
    }

    @Test
    void the_request_the_pipeline_understood_is_what_this_client_sends() throws Exception {
        QualityRequest request = MAPPER.treeToValue(fixture.get("request"), QualityRequest.class);

        JsonNode resent = MAPPER.valueToTree(request);
        JsonNode stored = fixture.get("request");

        // Field names, not ordering: a Java client that sends `required_fields` is a 422 at the
        // boundary, and one that drops `rawRecordCount` silently hides every record the run lost
        // before the pipeline saw them.
        assertThat(stored.fieldNames()).toIterable().allSatisfy(name ->
                assertThat(resent.has(name)).as(name).isTrue());
        assertThat(resent.has("rawRecordCount")).isTrue();
        assertThat(resent.has("requiredFields")).isTrue();
        assertThat(resent.has("deduplicationKeys")).isTrue();
        assertThat(resent.has("entityType")).isTrue();
        assertThat(request.records()).hasSize(6);
        assertThat(request.rawRecordCount()).isEqualTo(6);
    }

    @Test
    void every_record_binds_including_the_validity_flag_that_is_easy_to_lose() {
        assertThat(response.status()).isEqualTo("COMPLETED_WITH_WARNINGS");
        assertThat(response.records()).hasSize(6);
        assertThat(response.records()).allSatisfy(record -> {
            assertThat(record.values()).isNotNull();
            assertThat(record.sources()).isNotNull();
            assertThat(record.issues()).isNotNull();
            assertThat(record.normalizationNotes()).isNotNull();
        });
        // A record component called `isValid` is the one Jackson is most likely to bind to a
        // property named `valid`; if it did, every record would silently arrive as invalid.
        assertThat(response.records().stream().anyMatch(QualityResult.Record::isValid)).isTrue();
        assertThat(response.records().stream().noneMatch(QualityResult.Record::isValid)).isFalse();
    }

    @Test
    void provenance_survives_the_wire_in_both_directions_of_the_verification_flag() {
        List<QualityResult.Source> all = response.records().stream()
                .flatMap(record -> record.sources().stream()).toList();

        assertThat(all).isNotEmpty();
        assertThat(all.stream().anyMatch(QualityResult.Source::verifiedByTool)).isTrue();
        assertThat(all.stream().noneMatch(QualityResult.Source::verifiedByTool)).isFalse();
        assertThat(all).allSatisfy(source -> {
            assertThat(source.url()).isNotBlank();
            assertThat(source.sourceType()).isNotBlank();
        });
    }

    /** The two nullability cases that a primitive would silently invent: a link that is absent, and
     * a confidence that was never measured. */
    @Test
    void boxed_fields_stay_absent_instead_of_becoming_zero() {
        assertThat(response.records()).anySatisfy(record -> {
            assertThat(record.duplicateOf()).isNotNull();
            assertThat(record.matchType()).isIn("EXACT", "NORMALIZED", "ENTITY");
        });
        assertThat(response.records()).anySatisfy(record -> {
            assertThat(record.duplicateOf()).isNull();
            assertThat(record.confidence()).isNull();
            assertThat(record.sources()).isEmpty();
        });
    }

    @Test
    void a_conflict_arrives_with_both_values_and_the_rule_that_chose_between_them() {
        List<QualityResult.Conflict> conflicts = response.records().stream()
                .flatMap(record -> record.conflicts().stream()).toList();

        assertThat(conflicts).isNotEmpty();
        assertThat(conflicts).allSatisfy(conflict -> {
            assertThat(conflict.fieldKey()).isNotBlank();
            assertThat(conflict.resolvedBy()).isNotBlank();
            assertThat(conflict.keptSources()).isNotEmpty();
            assertThat(conflict.rejectedSources()).isNotEmpty();
        });
        assertThat(conflicts).anyMatch(conflict -> conflict.rejectedValue() != null);
    }

    @Test
    void the_dataset_arrives_as_typed_columns_and_the_row_indexes_it_claims() {
        assertThat(response.dataset().columns()).isNotEmpty();
        assertThat(response.dataset().columns()).allSatisfy(column -> {
            assertThat(column.key()).isNotBlank();
            assertThat(column.type()).isNotBlank();
        });
        assertThat(response.dataset().columns().stream()
                .filter(column -> "CURRENCY".equals(column.type())).count()).isEqualTo(1);
        assertThat(response.dataset().rows()).isNotEmpty();
        assertThat(response.dataset().rows().stream().map(QualityResult.Row::recordIndex))
                .allSatisfy(index -> assertThat(index).isBetween(0, 5));
    }

    @Test
    void the_quality_report_names_its_formula_because_a_score_without_one_is_a_claim() {
        QualityResult.Quality quality = response.quality();

        assertThat(quality).isNotNull();
        assertThat(quality.rawCount()).isEqualTo(6);
        assertThat(quality.qualityScore()).isNotNull();
        assertThat(quality.scoreBasis()).contains("equal-weight mean");
        assertThat(quality.scoreComponents()).containsKeys("completeness", "validity",
                "uniqueness", "consistency", "provenance");
    }

    @Test
    void every_stage_reports_itself_by_name_and_status() {
        assertThat(response.stages()).extracting(QualityResult.Stage::stage)
                .containsExactly("normalize", "validate", "deduplicate", "resolve", "merge",
                        "score");
        assertThat(response.stages()).allSatisfy(stage -> {
            assertThat(stage.status()).isIn("COMPLETED", "FAILED", "SKIPPED");
            assertThat(stage.metrics()).isNotNull();
        });
        assertThat(response.warnings()).isNotEmpty();
        assertThat(response.failureReason()).isNull();
    }

    @Test
    void a_value_the_pipeline_refused_to_guess_crosses_the_boundary_still_a_value() {
        // "79,90" is a European decimal or a thousands separator and the pipeline said so instead of
        // picking one. If the client reads it as null, the refusal has been turned into a loss.
        assertThat(response.records().stream()
                .flatMap(record -> record.values().values().stream())
                .filter(value -> value instanceof String)
                .map(String.class::cast)
                .anyMatch(value -> value.contains(","))).isTrue();
    }

    @Test
    void unknown_keys_on_the_wire_do_not_abort_the_call_but_are_not_a_contract_either() {
        Map<String, Object> shape = new java.util.LinkedHashMap<>();
        shape.put("status", "COMPLETED");
        shape.put("records", List.of());
        shape.put("dataset", Map.of("columns", List.of(), "rows", List.of()));
        shape.put("stages", List.of());
        shape.put("warnings", List.of());
        shape.put("aFieldJavaDoesNotHave", 1);

        QualityResult parsed = MAPPER.convertValue(shape, QualityResult.class);

        // The behaviour is a fact about this boundary worth pinning: Spring drops unknown keys, so
        // drift is caught by the fixture and by RequirementValidator's rules, never by a parse error.
        assertThat(parsed.status()).isEqualTo("COMPLETED");
        assertThat(parsed.records()).isEmpty();
        assertThat(parsed.quality()).isNull();
        assertThat(parsed.failureReason()).isNull();
    }
}
